### ISSUE TITLE
passwords's frequency are too large for 16 bits unsigned integer

### ISSUE THREAD

**Issue by Zeuh** [tylerchr/pwnedpass#1]
Hi, 

Maximum password frequency is 20760336 for the "123456" password. (SHA1 : 7C4A8D09CA3762AF61E59520943DC26494F8941B)

The frequency is stored in 2 bytes so maximum stored value is 65535.

This impact only the frequency's result of ~1000 most used passwords.

Best Regards

**Comment by tylerchr** [comment]
You're absolutely right about this, and it was an intentional cost-saving decision. My rationale is explained in the "linked" blog post that I apparently never actually posted (awkward!):

> Unfortunately there are some really bad passwords out there that have been compromised many more times than that, so I chose to store the number as a raw uint16 instead for a maximum value of 65,535. I figure any password compromised more times than that is totally hopeless, so storing a greater number doesn’t buy much.

I'll work on getting that post up; thanks for the notice.
