### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by ioistired** [tylerchr/pwnedpass#2]
Hi there. I'd like to use some of your code within my project, which uses the [BlueOak Model License v1.0.0](https://blueoakcouncil.org/license/1.0.0). However, without a license, I have no permission to do so. I'd like to suggest that you use the same license, as it [improves on existing permissive software licenses](https://blueoakcouncil.org/2019/03/06/model.html) in a lot of ways. Otherwise feel free to use whatever license you feel is best. Thanks for a great file format!

**Comment by tylerchr** [comment]
Thanks for the issue. I chose to use the BSD 3-clause license—the same one the Go project itself uses. I hope you find this code useful!
